// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
)

type Project struct {
	ID              int64
	Slug            string
	Name            string
	ShortCode       string
	ConsumerKey     string
	ConsumerSecret  string
	Passkey         string
	CallbackBaseUrl string
	CreatedAt       string
	LastActiveAt    sql.NullString
}

type ProjectSetting struct {
	ProjectID                 int64
	CallbackUrl               string
	StkTimeoutSeconds         int64
	C2bResponseType           string
	ExternalValidationDefault int64
}

type RequestLog struct {
	ID        int64
	ProjectID int64
	Kind      string
	Direction string
	Status    string
	Payload   string
	CreatedAt string
}
