// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_settings.sql

package repository

import (
	"context"
)

const createDefaultSettings = `-- name: CreateDefaultSettings :one
INSERT INTO "project_settings" ("project_id")
VALUES (?)
RETURNING project_id, callback_url, stk_timeout_seconds, c2b_response_type, external_validation_default, default_phone_number
`

func (q *Queries) CreateDefaultSettings(ctx context.Context, projectID int64) (ProjectSetting, error) {
	row := q.db.QueryRowContext(ctx, createDefaultSettings, projectID)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.CallbackUrl,
		&i.StkTimeoutSeconds,
		&i.C2bResponseType,
		&i.ExternalValidationDefault,
		&i.DefaultPhoneNumber,
	)
	return i, err
}

const getSettingsByProjectID = `-- name: GetSettingsByProjectID :one
SELECT project_id, callback_url, stk_timeout_seconds, c2b_response_type, external_validation_default, default_phone_number FROM "project_settings" WHERE "project_id" = ?
`

func (q *Queries) GetSettingsByProjectID(ctx context.Context, projectID int64) (ProjectSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByProjectID, projectID)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.CallbackUrl,
		&i.StkTimeoutSeconds,
		&i.C2bResponseType,
		&i.ExternalValidationDefault,
		&i.DefaultPhoneNumber,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE "project_settings"
SET "callback_url" = ?,
    "stk_timeout_seconds" = ?,
    "c2b_response_type" = ?,
    "external_validation_default" = ?,
    "default_phone_number" = ?
WHERE "project_id" = ?
RETURNING project_id, callback_url, stk_timeout_seconds, c2b_response_type, external_validation_default, default_phone_number
`

type UpdateSettingsParams struct {
	CallbackUrl               string
	StkTimeoutSeconds         int64
	C2bResponseType           string
	ExternalValidationDefault int64
	DefaultPhoneNumber        string
	ProjectID                 int64
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (ProjectSetting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.CallbackUrl,
		arg.StkTimeoutSeconds,
		arg.C2bResponseType,
		arg.ExternalValidationDefault,
		arg.DefaultPhoneNumber,
		arg.ProjectID,
	)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.CallbackUrl,
		&i.StkTimeoutSeconds,
		&i.C2bResponseType,
		&i.ExternalValidationDefault,
		&i.DefaultPhoneNumber,
	)
	return i, err
}
