// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package repository

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "projects" ("slug", "name", "short_code", "consumer_key", "consumer_secret", "passkey", "callback_base_url")
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, short_code, consumer_key, consumer_secret, passkey, callback_base_url, created_at, last_active_at
`

type CreateProjectParams struct {
	Slug            string
	Name            string
	ShortCode       string
	ConsumerKey     string
	ConsumerSecret  string
	Passkey         string
	CallbackBaseUrl string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.ShortCode,
		arg.ConsumerKey,
		arg.ConsumerSecret,
		arg.Passkey,
		arg.CallbackBaseUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ShortCode,
		&i.ConsumerKey,
		&i.ConsumerSecret,
		&i.Passkey,
		&i.CallbackBaseUrl,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM "projects" WHERE "slug" = ?
`

func (q *Queries) DeleteProject(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, slug)
	return err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, short_code, consumer_key, consumer_secret, passkey, callback_base_url, created_at, last_active_at FROM "projects" WHERE "slug" = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ShortCode,
		&i.ConsumerKey,
		&i.ConsumerSecret,
		&i.Passkey,
		&i.CallbackBaseUrl,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, short_code, consumer_key, consumer_secret, passkey, callback_base_url, created_at, last_active_at FROM "projects"
ORDER BY COALESCE("last_active_at", "created_at") DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ShortCode,
			&i.ConsumerKey,
			&i.ConsumerSecret,
			&i.Passkey,
			&i.CallbackBaseUrl,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateProjectCredentials = `-- name: RegenerateProjectCredentials :one
UPDATE "projects"
SET "consumer_key" = ?, "consumer_secret" = ?, "passkey" = ?
WHERE "slug" = ?
RETURNING id, slug, name, short_code, consumer_key, consumer_secret, passkey, callback_base_url, created_at, last_active_at
`

type RegenerateProjectCredentialsParams struct {
	ConsumerKey    string
	ConsumerSecret string
	Passkey        string
	Slug           string
}

func (q *Queries) RegenerateProjectCredentials(ctx context.Context, arg RegenerateProjectCredentialsParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, regenerateProjectCredentials,
		arg.ConsumerKey,
		arg.ConsumerSecret,
		arg.Passkey,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ShortCode,
		&i.ConsumerKey,
		&i.ConsumerSecret,
		&i.Passkey,
		&i.CallbackBaseUrl,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM "projects" WHERE "slug" = ?)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchProjectLastActive = `-- name: TouchProjectLastActive :exec
UPDATE "projects"
SET "last_active_at" = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE "slug" = ?
`

func (q *Queries) TouchProjectLastActive(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, touchProjectLastActive, slug)
	return err
}
