// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_log.sql

package repository

import (
	"context"
	"database/sql"
)

const clearRequestLog = `-- name: ClearRequestLog :exec
DELETE FROM "request_log" WHERE "project_id" = ?
`

func (q *Queries) ClearRequestLog(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, clearRequestLog, projectID)
	return err
}

const createRequestLogEntry = `-- name: CreateRequestLogEntry :one
INSERT INTO "request_log" ("project_id", "correlation_id", "kind", "direction", "status", "outcome", "attempts", "payload")
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, correlation_id, kind, direction, status, outcome, attempts, payload, created_at
`

type CreateRequestLogEntryParams struct {
	ProjectID     int64
	CorrelationID sql.NullString
	Kind          string
	Direction     string
	Status        string
	Outcome       sql.NullString
	Attempts      int64
	Payload       string
}

func (q *Queries) CreateRequestLogEntry(ctx context.Context, arg CreateRequestLogEntryParams) (RequestLog, error) {
	row := q.db.QueryRowContext(ctx, createRequestLogEntry,
		arg.ProjectID,
		arg.CorrelationID,
		arg.Kind,
		arg.Direction,
		arg.Status,
		arg.Outcome,
		arg.Attempts,
		arg.Payload,
	)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CorrelationID,
		&i.Kind,
		&i.Direction,
		&i.Status,
		&i.Outcome,
		&i.Attempts,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestLogEntries = `-- name: ListRequestLogEntries :many
SELECT id, project_id, correlation_id, kind, direction, status, outcome, attempts, payload, created_at FROM "request_log"
WHERE "project_id" = ?
ORDER BY "created_at" DESC
LIMIT ?
`

type ListRequestLogEntriesParams struct {
	ProjectID int64
	Limit     int64
}

func (q *Queries) ListRequestLogEntries(ctx context.Context, arg ListRequestLogEntriesParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogEntries, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CorrelationID,
			&i.Kind,
			&i.Direction,
			&i.Status,
			&i.Outcome,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestLogEntriesByKind = `-- name: ListRequestLogEntriesByKind :many
SELECT id, project_id, correlation_id, kind, direction, status, outcome, attempts, payload, created_at FROM "request_log"
WHERE "project_id" = ? AND "kind" = ?
ORDER BY "created_at" DESC
LIMIT ?
`

type ListRequestLogEntriesByKindParams struct {
	ProjectID int64
	Kind      string
	Limit     int64
}

func (q *Queries) ListRequestLogEntriesByKind(ctx context.Context, arg ListRequestLogEntriesByKindParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogEntriesByKind, arg.ProjectID, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CorrelationID,
			&i.Kind,
			&i.Direction,
			&i.Status,
			&i.Outcome,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestLogEntriesFirstPage = `-- name: ListRequestLogEntriesFirstPage :many
SELECT id, project_id, correlation_id, kind, direction, status, outcome, attempts, payload, created_at FROM "request_log"
WHERE "project_id" = ?
ORDER BY "id" DESC
LIMIT ?
`

type ListRequestLogEntriesFirstPageParams struct {
	ProjectID int64
	Limit     int64
}

func (q *Queries) ListRequestLogEntriesFirstPage(ctx context.Context, arg ListRequestLogEntriesFirstPageParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogEntriesFirstPage, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CorrelationID,
			&i.Kind,
			&i.Direction,
			&i.Status,
			&i.Outcome,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestLogEntriesNextPage = `-- name: ListRequestLogEntriesNextPage :many
SELECT id, project_id, correlation_id, kind, direction, status, outcome, attempts, payload, created_at FROM "request_log"
WHERE "project_id" = ? AND "id" < ?
ORDER BY "id" DESC
LIMIT ?
`

type ListRequestLogEntriesNextPageParams struct {
	ProjectID int64
	ID        int64
	Limit     int64
}

func (q *Queries) ListRequestLogEntriesNextPage(ctx context.Context, arg ListRequestLogEntriesNextPageParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogEntriesNextPage, arg.ProjectID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CorrelationID,
			&i.Kind,
			&i.Direction,
			&i.Status,
			&i.Outcome,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
