// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_log.sql

package repository

import (
	"context"
)

const clearRequestLog = `-- name: ClearRequestLog :exec
DELETE FROM "request_log" WHERE "project_id" = ?
`

func (q *Queries) ClearRequestLog(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, clearRequestLog, projectID)
	return err
}

const createRequestLogEntry = `-- name: CreateRequestLogEntry :one
INSERT INTO "request_log" ("project_id", "kind", "direction", "status", "attempts", "payload")
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, project_id, kind, direction, status, attempts, payload, created_at
`

type CreateRequestLogEntryParams struct {
	ProjectID int64
	Kind      string
	Direction string
	Status    string
	Attempts  int64
	Payload   string
}

func (q *Queries) CreateRequestLogEntry(ctx context.Context, arg CreateRequestLogEntryParams) (RequestLog, error) {
	row := q.db.QueryRowContext(ctx, createRequestLogEntry,
		arg.ProjectID,
		arg.Kind,
		arg.Direction,
		arg.Status,
		arg.Attempts,
		arg.Payload,
	)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Direction,
		&i.Status,
		&i.Attempts,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestLogEntries = `-- name: ListRequestLogEntries :many
SELECT id, project_id, kind, direction, status, attempts, payload, created_at FROM "request_log"
WHERE "project_id" = ?
ORDER BY "created_at" DESC
LIMIT ?
`

type ListRequestLogEntriesParams struct {
	ProjectID int64
	Limit     int64
}

func (q *Queries) ListRequestLogEntries(ctx context.Context, arg ListRequestLogEntriesParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogEntries, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Direction,
			&i.Status,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
